### ISSUE TITLE
vendor.* files in /vendor folder?

### ISSUE THREAD

**Issue by alejandronanez** [UltimateAngular/angular-fundamentals-seed#1]
Hey, I was wondering, is it necessary to exclude `vendor.js` / `vendor.map` / `vendor-manifes.json` from git?

Thanks!

**Comment by toddmotto** [comment]
You only need them locally on your machine - it means any updates to package.json you want to make yourself can be done, similarly I can also update new versions and notify everyone to update their seeds should they wish to. Guess it's not really a huge difference either way. 

@toddmotto
