### ISSUE TITLE
Why Choose Yarn Over Angular CLI

### ISSUE THREAD

**Issue by johnmiroki** [UltimateAngular/angular-fundamentals-seed#7]
I'm just beginning the course and a bit surprised to see yarn introduced in the course instead of Angular CLI. I'd like to learn about the reason why author chose one over the other. Thanks!

**Comment by toddmotto** [comment]
At the time of recording the CLI wasn't too stable, and a simple webpack config was a better option to mitigate any CLI version issues and keep things as basic as possible - to focus on Angular :)
